### ISSUE TITLE
Commit Error - Help

### ISSUE THREAD

**Issue by samantha-nickerson** [gbales11/greatlakesalliance#31]
As soon as you left, I tried to sync from my computer and it caused a huge error making our style.css really messed up. How do we go back to the commit that you did on Logan's computer? 

@tiffanytse

**Comment by samantha-nickerson** [comment]
Everything looks normal on my local computer but the actual website is completely ruined. If possible, I need to undo the last two commits that I made. 

http://giuliateresa.ca/greatlakesalliance/

**Comment by samantha-nickerson** [comment]
We reverted the commit and fixed the issue! Sorry to bother you.

**Comment by tiffanytse** [comment]
Good to hear @samantha-nickerson
